version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.1.0
    steps:
      - checkout
      - run: echo "Hello"

  build2:
    docker:
      - image: circleci/node:8.1.0
    steps:
      - checkout
      - run: echo "A second one"

workflows:
  version: 2
  flows:
    jobs:
      - build
      - build2
